<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Permission::insert([
            [
                'role_id' => 1,
                'user_view' => 1,
                'user_create' => 1,
                'user_edit' => 1,
                'user_delete' => 1,
                'menu_view' => 1,
                'menu_create' => 1,
                'menu_edit' => 1,
                'menu_delete' => 1,
                'submenu_view' => 1,
                'submenu_create' => 1,
                'submenu_edit' => 1,
                'submenu_delete' => 1,
                'content_view' => 1,
                'content_create' => 1,
                'content_edit' => 1,
                'content_delete' => 1,
                'aboutus_view' => 1,
                'aboutus_create' => 1,
                'aboutus_edit' => 1,
                'aboutus_delete' => 1,
                'slideshow_view' => 1,
                'slideshow_create' => 1,
                'slideshow_edit' => 1,
                'slideshow_delete' => 1,
                'service_view' => 1,
                'service_create' => 1,
                'service_edit' => 1,
                'service_delete' => 1,
                'trusted_view' => 1,
                'trusted_create' => 1,
                'trusted_edit' => 1,
                'trusted_delete' => 1,
                'commentclient_view' => 1,
                'commentclient_create' => 1,
                'commentclient_edit' => 1,
                'commentclient_delete' => 1,
                'categorynews_view' => 1,
                'categorynews_create' => 1,
                'categorynews_edit' => 1,
                'categorynews_delete' => 1,
                'news_view' => 1,
                'news_create' => 1,
                'news_edit' => 1,
                'news_delete' => 1,
                'faq_view' => 1,
                'faq_create' => 1,
                'faq_edit' => 1,
                'faq_delete' => 1,
                'contactus_view' => 1,
                'contactus_create' => 1,
                'contactus_edit' => 1,
                'contactus_delete' => 1,
                'information_view' => 1,
                'information_create' => 1,
                'information_edit' => 1,
                'information_delete' => 1,
                'consultation_view' => 1,
                'consultation_create' => 1,
                'consultation_edit' => 1,
                'consultation_delete' => 1,
                'contactour_view' => 1,
                'contactour_create' => 1,
                'contactour_edit' => 1,
                'contactour_delete' => 1
            ],
            [
                'role_id' => 2,
                'user_view' => 1,
                'user_create' => 1,
                'user_edit' => 1,
                'user_delete' => 1,
                'menu_view' => 1,
                'menu_create' => 1,
                'menu_edit' => 1,
                'menu_delete' => 1,
                'submenu_view' => 1,
                'submenu_create' => 1,
                'submenu_edit' => 1,
                'submenu_delete' => 1,
                'content_view' => 1,
                'content_create' => 1,
                'content_edit' => 1,
                'content_delete' => 1,
                'aboutus_view' => 1,
                'aboutus_create' => 1,
                'aboutus_edit' => 1,
                'aboutus_delete' => 1,
                'slideshow_view' => 1,
                'slideshow_create' => 1,
                'slideshow_edit' => 1,
                'slideshow_delete' => 1,
                'service_view' => 1,
                'service_create' => 1,
                'service_edit' => 1,
                'service_delete' => 1,
                'trusted_view' => 1,
                'trusted_create' => 1,
                'trusted_edit' => 1,
                'trusted_delete' => 1,
                'commentclient_view' => 1,
                'commentclient_create' => 1,
                'commentclient_edit' => 1,
                'commentclient_delete' => 1,
                'categorynews_view' => 1,
                'categorynews_create' => 1,
                'categorynews_edit' => 1,
                'categorynews_delete' => 1,
                'news_view' => 1,
                'news_create' => 1,
                'news_edit' => 1,
                'news_delete' => 1,
                'faq_view' => 1,
                'faq_create' => 1,
                'faq_edit' => 1,
                'faq_delete' => 1,
                'contactus_view' => 1,
                'contactus_create' => 1,
                'contactus_edit' => 1,
                'contactus_delete' => 1,
                'information_view' => 1,
                'information_create' => 1,
                'information_edit' => 1,
                'information_delete' => 1,
                'consultation_view' => 1,
                'consultation_create' => 1,
                'consultation_edit' => 1,
                'consultation_delete' => 1,
                'contactour_view' => 1,
                'contactour_create' => 1,
                'contactour_edit' => 1,
                'contactour_delete' => 1
            ],
        ]);
    }
}
